# Generated by Django 6.0.7 on 2026-07-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.JSONField(blank=True, default=list)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='auth.group')),
            ],
        ),
    ]
