# Generated by Django 6.0.7 on 2026-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('class_1', models.BooleanField(default=False, verbose_name='Class 1')),
                ('class_2', models.BooleanField(default=False, verbose_name='Class 2')),
                ('class_3', models.BooleanField(default=False, verbose_name='Class 3')),
                ('class_4', models.BooleanField(default=False, verbose_name='Class 4')),
                ('class_5', models.BooleanField(default=False, verbose_name='Class 5')),
                ('class_6', models.BooleanField(default=False, verbose_name='Class 6')),
                ('class_e', models.BooleanField(default=False, verbose_name='Class E')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
