# Generated by Django 6.0.7 on 2026-07-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('E', 'Class E')], max_length=1)),
                ('is_running', models.BooleanField(default=False)),
                ('age_from', models.PositiveIntegerField(blank=True, help_text='Starting age, e.g. 6', null=True)),
                ('age_to', models.PositiveIntegerField(blank=True, help_text='Ending age, e.g. 7', null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='competitions.competition')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('competition', 'code')},
            },
        ),
    ]
