# Generated by Django 6.0.7 on 2026-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_dynamic_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_multiple_classes',
            field=models.BooleanField(default=False, help_text='Manual assignment only: may a participant be in more than one class.'),
        ),
        migrations.AddField(
            model_name='competition',
            name='assignment_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('age', 'Based on age')], default='manual', help_text='How participants are assigned to classes.', max_length=20),
        ),
        migrations.AddField(
            model_name='competitionclass',
            name='allow_multiple_entries',
            field=models.BooleanField(default=False, help_text='Manual assignment only: may a participant be entered into this class more than once.'),
        ),
    ]
