# Generated by Django 6.0.7 on 2026-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competition_allow_multiple_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='start_pattern',
            field=models.JSONField(blank=True, default=list, help_text='The order participants take their runs, as pattern blocks (see apps/competitions/startpattern.py). Replayed for every run.'),
        ),
    ]
