# Generated by Django 6.0.7 on 2026-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_competition_start_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionclass',
            name='scoring_method',
            field=models.CharField(choices=[('aggregate', 'Aggregate times'), ('regularity', 'Regularity test')], default='aggregate', help_text="How this class's counted runs are turned into a result.", max_length=20),
        ),
    ]
