# Generated by Django 6.0.7 on 2026-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_competitionclass_scoring_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='max_penalty_per_task',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Upper bound on the seconds a single task can add.', null=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='penalties_enabled',
            field=models.BooleanField(default=True, help_text='Show the penalties screen during timing so penalties can be entered per run.'),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='pylon_penalty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds added per pylon hit.', null=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='requires_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='requires_club',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='requires_co_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='requires_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='requires_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='requires_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='stop_line_penalty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds added for missing the stop line.', null=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='task_penalty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds added for a failed task.', null=True),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='tie_break',
            field=models.CharField(choices=[('fastest_run', 'Fastest run time'), ('manual', 'Manual')], default='fastest_run', help_text='How equal results are separated.', max_length=20),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='timing_precision',
            field=models.PositiveSmallIntegerField(choices=[(1, '1/10 s'), (2, '1/100 s'), (3, '1/1000 s')], default=2, help_text='Resolution of the timing device.'),
        ),
    ]
