# Generated by Django 6.0.7 on 2026-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_competitiontype_max_penalty_per_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='requires_license',
            field=models.BooleanField(default=True),
        ),
    ]
