# Generated by Django 6.0.7 on 2026-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_competitiontype_requires_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionclass',
            name='scoring_method',
            field=models.CharField(choices=[('aggregate', 'Aggregate times'), ('best_run', 'Best run only'), ('regularity', 'Regularity test')], default='aggregate', help_text="How this class's counted runs are turned into a result.", max_length=20),
        ),
    ]
