# Generated by Django 6.0.7 on 2026-07-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_competitionclass_scoring_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='penalties_by_marshal_posts',
            field=models.BooleanField(default=False, help_text='Marshal posts enter penalties for their own area, instead of the timekeeper entering every penalty.'),
        ),
        migrations.CreateModel(
            name='MarshalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='1-based post number, in setup order.')),
                ('tasks', models.CharField(blank=True, help_text='Task numbers this post watches, e.g. “1, 5, 11-15”.', max_length=200)),
                ('handles_stop_line', models.BooleanField(default=False, help_text='This post also judges the stop line (at most one post per competition).')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marshal_posts', to='competitions.competition')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('competition', 'number')},
            },
        ),
    ]
