# Generated by Django 6.0.7 on 2026-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_competition_penalties_by_marshal_posts_marshalpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='auto_timing_order',
            field=models.JSONField(blank=True, default=list, help_text='Manual override of the Auto timing start order, as a list of slot keys. Empty means the computed order (run order × start pattern) is used.'),
        ),
    ]
