# Generated by Django 6.0.7 on 2026-07-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_competition_auto_timing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='marshalpost',
            name='claim_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marshalpost',
            name='claim_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
