# Generated by Django 6.0.7 on 2026-07-28 21:25

from django.db import migrations, models


def keep_one_active(apps, schema_editor):
    """Leave exactly one competition active before the constraint goes on.

    Nothing enforced this before, so a database can already hold two — set by the
    Django admin, or by an import that raced a switch. The constraint would then
    refuse to apply and the upgrade would stop dead on race morning. The one kept
    is the one `Competition.get_current()` was already serving: `filter(
    is_active=True).first()` under the model's own `-date` ordering.
    """
    Competition = apps.get_model('competitions', 'Competition')
    active = list(Competition.objects.filter(is_active=True).order_by('-date', 'pk'))
    if len(active) > 1:
        Competition.objects.filter(
            pk__in=[c.pk for c in active[1:]]
        ).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_marshalpost_claim_seen_marshalpost_claim_token'),
    ]

    operations = [
        # Before the constraint, not after: it cannot be added to a table that
        # already breaks it.
        migrations.RunPython(keep_one_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='competition',
            name='start_pattern',
            field=models.JSONField(blank=True, default=list, help_text='The order participants take their runs, as pattern blocks (see apps/competitions/startpattern.py). Replayed for every run. Empty means no pattern — Auto timing then asks for one and the other screens carry on without it.'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_competition'),
        ),
    ]
