# Generated by Django 6.0.7 on 2026-08-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_alter_competition_start_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenCompetitionType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.competitiontype',),
        ),
        migrations.AddField(
            model_name='competition',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="When the event was signed off. An archived competition is read-only and is evaluated by the settings stored in archived_rules rather than by its type's live ones (see apps/competitions/archiving.py).", null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='archived_rules',
            field=models.JSONField(blank=True, default=dict, help_text="The competition type's settings as they stood when the event was archived. Empty for a live competition, which follows its type."),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='max_penalty_per_task',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Upper bound on the seconds a single task can add.', null=True, verbose_name='Max per task'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='penalties_enabled',
            field=models.BooleanField(default=True, help_text='Show the penalties screen during timing so penalties can be entered per run.', verbose_name='Enter penalties during the race'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='pylon_penalty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds added per pylon hit.', null=True, verbose_name='Pylon'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_address',
            field=models.BooleanField(default=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_club',
            field=models.BooleanField(default=True, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_co_driver',
            field=models.BooleanField(default=False, verbose_name='Co-driver'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_email',
            field=models.BooleanField(default=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_license',
            field=models.BooleanField(default=True, verbose_name='Licence number'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_phone',
            field=models.BooleanField(default=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='requires_vehicle',
            field=models.BooleanField(default=False, verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='stop_line_penalty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds added for missing the stop line.', null=True, verbose_name='Stop line'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='task_penalty',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Seconds added for a failed task.', null=True, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='tie_break',
            field=models.CharField(choices=[('fastest_run', 'Fastest run time'), ('manual', 'Manual')], default='fastest_run', help_text='How equal results are separated.', max_length=20, verbose_name='Tie-break'),
        ),
        migrations.AlterField(
            model_name='competitiontype',
            name='timing_precision',
            field=models.PositiveSmallIntegerField(choices=[(1, '1/10 s'), (2, '1/100 s'), (3, '1/1000 s')], default=2, help_text='Resolution of the timing device.', verbose_name='Timing precision'),
        ),
        migrations.CreateModel(
            name='ArchivedStarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_pk', models.PositiveIntegerField(help_text='The EventEntry id this competitor had while the event was live.')),
                ('participant_pk', models.PositiveIntegerField(help_text='The Participant id, kept so stored slot keys and tie resolutions still name the same person.')),
                ('bib_number', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(default=dict, help_text="The participant's own fields as they read on the day (see apps/competitions/archiving.py).")),
                ('class_pks', models.JSONField(default=list, help_text='CompetitionClass ids this competitor was entered in, in order, with repeats — a class entered twice appears twice.')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_starters', to='competitions.competition')),
            ],
            options={
                'ordering': ['bib_number', 'entry_pk'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'entry_pk'), name='one_archived_row_per_entry')],
            },
        ),
    ]
