# Generated by Django 6.0.7 on 2026-08-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_alter_competition_start_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenCompetitionType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('competitions.competitiontype',),
        ),
        migrations.AddField(
            model_name='competition',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="When the event was signed off. An archived competition is read-only and is evaluated by the settings stored in archived_rules rather than by its type's live ones (see apps/competitions/archiving.py).", null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='archived_rules',
            field=models.JSONField(blank=True, default=dict, help_text="The competition type's settings as they stood when the event was archived. Empty for a live competition, which follows its type."),
        ),
    ]
