# Generated by Django 6.0.7 on 2026-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_frozencompetitiontype_competition_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='uses_draw_numbers',
            field=models.BooleanField(default=False, help_text='The registration desk gives each participant a drawn number, and bibs are handed out from it per class (see Bib assignment).'),
        ),
        migrations.AddField(
            model_name='competitionclass',
            name='registration_closed_at',
            field=models.DateTimeField(blank=True, help_text="When this class's registration was closed and its bibs assigned from the drawn numbers. Null while it is still open (or when the competition does not use drawn numbers at all).", null=True),
        ),
    ]
