"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Everything this app *writes* while it runs — the event database, uploaded logos,
# the single-server lock, the unrecorded-times recovery file. A checkout keeps them
# beside the code (BASE_DIR), which is what a developer expects; the packaged
# Windows build (build/) points this at %LOCALAPPDATA%\SlalomTiming\data instead,
# because the code there is replaced wholesale by the next installer and the
# database is the event. Anything written at runtime belongs under here, never
# under BASE_DIR — config/tests.py holds the line.
DATA_DIR = Path(os.environ.get('SLALOM_DATA_DIR') or BASE_DIR)


def _env_bool(name, default=False):
    """Read a boolean from the environment ("1/true/yes/on" -> True)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """Read a comma-separated list from the environment (empties dropped)."""
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


def _env_int(name, default):
    """Read an integer from the environment, falling back on anything unreadable."""
    try:
        return int(os.environ[name])
    except (KeyError, ValueError):
        return default


# --- Core security settings (see config/.env.example for deployment) ---
# In production every one of these MUST come from the environment.

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local use; set DJANGO_DEBUG=False in any deployment.
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

# Where a development checkout keeps its generated signing key. Under DATA_DIR
# (gitignored) so it is never committed and never shipped.
DEV_SECRET_KEY_FILE = DATA_DIR / '.secret_key'


def _development_secret_key():
    """A signing key for *this checkout*, generated once and kept in DATA_DIR.

    There used to be a literal key in this file. This repository is public, so
    that key is public: anyone who has read it can forge anything signed with it —
    a session cookie for any account, a password-reset token. A development server
    on a shared network was one `git clone` away from a forged superuser session,
    and no amount of history rewriting takes a published key back.

    So each checkout now mints its own on first use. It is still a *development*
    key and is never consulted with DEBUG off: a deployment must set
    DJANGO_SECRET_KEY in its environment (enforced below).
    """
    try:
        existing = DEV_SECRET_KEY_FILE.read_text(encoding='utf-8').strip()
        if existing:
            return existing
    except OSError:
        pass
    # stdlib only: this runs while the settings module is still being executed,
    # so nothing here may reach back into django.conf.
    import secrets as _secrets

    key = ''.join(
        _secrets.choice('abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')
        for _ in range(50)
    )
    try:
        DEV_SECRET_KEY_FILE.parent.mkdir(parents=True, exist_ok=True)
        DEV_SECRET_KEY_FILE.write_text(key, encoding='utf-8')
        os.chmod(DEV_SECRET_KEY_FILE, 0o600)  # best effort; a no-op on Windows
    except OSError:
        # A read-only checkout: a key that lasts one process still beats a shared
        # one. Sessions won't survive a restart, which is a development problem.
        pass
    return key


_ENV_SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()

if _ENV_SECRET_KEY:
    SECRET_KEY = _ENV_SECRET_KEY
elif DEBUG:
    SECRET_KEY = _development_secret_key()
else:
    # A deployment that forgot the key must fail loudly here rather than run
    # unsafely (`check --deploy` only warns, and a warning is easy to miss on race
    # morning). The generated development key is deliberately not offered as a
    # fallback: it lives beside the database, which gets copied about.
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is not set and DEBUG is False. A deployment must be '
        'given its own key; generate one with:\n'
        '  uv run python -c "from django.core.management.utils import '
        'get_random_secret_key as g; print(g())"'
    )

# Hosts/domains this site may serve. Required (non-empty) once DEBUG is off.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
# Left empty with DEBUG off, the app *starts* and then refuses every request with
# DisallowedHost — which on race morning reads as "the server is broken" from every
# phone at the venue at once. It is refused at startup instead, but in config/asgi.py
# rather than here: this setting only means anything to something that serves
# requests, and `collectstatic` (a required release step, and the packaged build's
# own) legitimately runs with DEBUG off and no hosts at all.

# Origins allowed to send authenticated POSTs over HTTPS (the live domain(s)),
# e.g. "https://timing.example.org". Needed for form posts from the real host.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    # 'daphne' must come first: it replaces `runserver` with an ASGI-capable
    # version so WebSocket upgrades (the live dashboard) actually work.
    # Without it, runserver silently falls back to plain WSGI and every
    # WebSocket connection fails immediately.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'apps.accounts',
    'apps.competitions',
    'apps.participants',
    'apps.timing',
    'apps.results',
    'apps.transfer',
]

# Whether the CSP is sent as Report-Only (nothing blocked, violations logged to
# the browser console). For finding out what a new page broke without breaking it
# in front of an operator — not a setting to deploy with. See config/csp.py.
CSP_REPORT_ONLY = _env_bool('DJANGO_CSP_REPORT_ONLY', default=False)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves everything under STATIC_ROOT (compressed + far-future cached) from the
    # app process itself. `runserver` stops serving /static/ once DEBUG is off, so
    # without this a real deployment renders with no CSS and no JS at all. Must sit
    # directly below SecurityMiddleware and above everything else.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Content-Security-Policy (SEC-11). Below WhiteNoise — a static file needs no
    # policy and WhiteNoise answers those without going further — but above
    # everything that renders a page, so an error page carries it too.
    'config.csp.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Resolves the active language (session -> cookie -> Accept-Language ->
    # LANGUAGE_CODE) so {% trans %} and gettext render in the chosen language.
    # Must sit after SessionMiddleware (reads the language from the session) and
    # before CommonMiddleware.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Login required everywhere + role-based page gating (see apps/accounts).
    # Must sit after AuthenticationMiddleware (needs request.user).
    'apps.accounts.middleware.AccessControlMiddleware',
    # Who changed what (SEC-9). Innermost, so it sees request.user and the
    # resolved view, and only records requests the gate above let through.
    'apps.audit.AuditMiddleware',
]

# Authentication redirects (apps.accounts provides the login/logout views).
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Shared secret an *unauthenticated* HTTP timing device must present on
# timing:signal (header "X-Device-Token"). Empty in local dev: while DEBUG is on
# the endpoint stays open, but a logged-in operator's browser (the Simulator)
# always works via its session. Set this in production so the one open write
# endpoint isn't world-writable. The real CP540 doesn't use this door (it feeds
# record_signal() directly from the reader thread), so this only matters for a
# future networked HTTP device.
TIMING_DEVICE_TOKEN = os.environ.get('TIMING_DEVICE_TOKEN', '')

# --- Production hardening ---
# All data pages already require a login (apps.accounts.AccessControlMiddleware),
# so nothing is world-readable. These transport-level protections switch on once
# DEBUG is off (a real deployment).
#
# HTTPS is not optional here, it is the default, and there is exactly ONE way to
# turn it off: DJANGO_ALLOW_PLAIN_HTTP. A race-day Wi-Fi with marshals' phones on
# it is not a trusted network — on plain HTTP every password and every timekeeper's
# session cookie is readable by anything else on that network. deploy/Caddyfile
# terminates TLS with a local CA (no internet, no public domain needed); Tailscale
# is the other supported answer. See DEPLOYMENT.md.
#
# It is one flag rather than a per-setting override on purpose: nobody should end up
# on plain HTTP by turning off "secure cookies" and not realising what else that
# implies. The two older names are refused below rather than ignored.
ALLOW_PLAIN_HTTP = _env_bool('DJANGO_ALLOW_PLAIN_HTTP', default=False)

if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured

    for _retired in ('DJANGO_SECURE_SSL_REDIRECT', 'DJANGO_SECURE_COOKIES'):
        if os.environ.get(_retired) and not _env_bool(_retired, default=True):
            raise ImproperlyConfigured(
                f'{_retired}=False is no longer honoured on its own. Running this app '
                'on plain HTTP is a single, explicit decision: set '
                'DJANGO_ALLOW_PLAIN_HTTP=True (and read the TLS section of '
                'DEPLOYMENT.md first — it is almost never the right answer).'
            )

    # Trust the X-Forwarded-Proto header from a TLS-terminating reverse proxy.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = not ALLOW_PLAIN_HTTP
    # …except the health check. A local check does `curl http://127.0.0.1:8000/healthz`
    # — the run-book, the unit file and any uptime probe on the box itself — and a 301
    # to a hostname it isn't asking for makes every one of them report a healthy
    # server as broken. It is safe to exempt precisely because of what it isn't: no
    # cookie, no credential, no personal data, one word of output (config/health.py).
    # Nothing else may be added to this list without the same argument.
    SECURE_REDIRECT_EXEMPT = [r'^healthz$']
    SESSION_COOKIE_SECURE = not ALLOW_PLAIN_HTTP
    CSRF_COOKIE_SECURE = not ALLOW_PLAIN_HTTP
    # HSTS pins the hostname to HTTPS in every browser that saw the header, and it
    # cannot be taken back before it expires. On a venue hostname served with a local
    # CA that makes a long default a trap rather than a protection (the machine's name
    # gets reused; a laptop that once opened `timing.local` here would refuse plain
    # HTTP at the next venue for the rest of the year). So: short by default, long
    # only once you have a stable public domain and mean it.
    SECURE_HSTS_SECONDS = 0 if ALLOW_PLAIN_HTTP else _env_int('DJANGO_HSTS_SECONDS', 300)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    # Preloading is for public domains submitted to the browsers' list; on a LAN name
    # it does nothing but make the pin permanent. Opt in with a real domain.
    SECURE_HSTS_PRELOAD = _env_bool('DJANGO_HSTS_PRELOAD', default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # the JS timing views read the CSRF cookie
    X_FRAME_OPTIONS = 'DENY'

    if not SECURE_HSTS_PRELOAD:
        # security.W021 asks for SECURE_HSTS_PRELOAD; see above for why this
        # deployment shape says no. Silenced so `check --deploy` stays clean and a
        # real warning stands out on race morning.
        SILENCED_SYSTEM_CHECKS = ['security.W021']

    if ALLOW_PLAIN_HTTP:
        # Said out loud on every management command and in the server log, because
        # this is the one setting that quietly undoes the rest of this block.
        import sys

        print(
            'WARNING: DJANGO_ALLOW_PLAIN_HTTP is set — this server is running '
            'without TLS. Passwords and session cookies are readable by anything '
            'else on the network. See the TLS section of DEPLOYMENT.md.',
            file=sys.stderr,
        )

# --- Sessions ---
# Django's default is two weeks, which is a long time to leave a signed-in session on
# a shared timekeeping laptop or a marshal's personal phone. An event day is the unit
# that matters. Not refreshed per request on purpose (SESSION_SAVE_EVERY_REQUEST
# stays off): that would add a database write to every poll of the live views, and
# this system's scarce resource is the SQLite write lock the timing device needs.
SESSION_COOKIE_AGE = _env_int('DJANGO_SESSION_HOURS', 12) * 3600

# --- Login throttling (apps/accounts/throttle.py) ---
# Attempts per (username, IP) before that pair is refused, and for how long. The
# counters live in the cache below; both are env-settable so a locked-out timekeeper
# can be let back in mid-event without touching code.
LOGIN_MAX_ATTEMPTS = _env_int('DJANGO_LOGIN_MAX_ATTEMPTS', 10)
# ...and per IP across every username, which is what stops one host working
# through a list of accounts. Higher, because a venue laptop may be several
# people's browser.
LOGIN_MAX_ATTEMPTS_PER_HOST = _env_int('DJANGO_LOGIN_MAX_ATTEMPTS_PER_HOST', 50)
LOGIN_LOCKOUT_SECONDS = _env_int('DJANGO_LOGIN_LOCKOUT_SECONDS', 300)

# --- Logging ---
# There was no LOGGING at all, which had two consequences nobody could see. Python's
# last-resort handler emits WARNING and above, so `throttle.note_success` ("who
# signed in") was written at INFO and silently dropped — the login audit trail the
# throttle module exists to provide did not reach anywhere. And nothing went to a
# *file*: the packaged Windows build runs Daphne in a console window that is closed
# at the end of the day, so failed logins and "this time could not be stored"
# vanished with it.
#
# So: a rotating file under DATA_DIR (the directory that survives an upgrade),
# alongside the console. Deliberately small — three files of 2 MB is months of a
# club's events, and nothing here is chatty.
LOG_DIR = Path(os.environ.get('DJANGO_LOG_DIR') or DATA_DIR / 'logs')
LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()
# The audit trail keeps its own file. It answers a different question from the
# application log ("who changed this result?" rather than "what went wrong?"),
# it is the one a protest is settled from, and mixing it into the general log
# would bury it — so it rotates on its own budget and is downloaded on its own.
AUDIT_LOG_FILE = LOG_DIR / 'audit.log'
AUDIT_LOG_MAX_BYTES = _env_int('DJANGO_AUDIT_LOG_MAX_BYTES', 5 * 1024 * 1024)
AUDIT_LOG_BACKUPS = _env_int('DJANGO_AUDIT_LOG_BACKUPS', 5)

try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    _log_file_ok = True
except OSError:
    # A read-only or unwritable data directory must not stop the server coming up;
    # the console handler still works.
    _log_file_ok = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'app': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
        # No level and no logger name: every line is the same kind of thing, and
        # what matters is that a person can read a column of them.
        'audit': {
            'format': '{asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'app',
        },
        **({'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'slalomtiming.log'),
            'maxBytes': 2 * 1024 * 1024,
            'backupCount': 3,
            'encoding': 'utf-8',
            'formatter': 'app',
        }} if _log_file_ok else {}),
        **({'audit': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(AUDIT_LOG_FILE),
            'maxBytes': AUDIT_LOG_MAX_BYTES,
            'backupCount': AUDIT_LOG_BACKUPS,
            'encoding': 'utf-8',
            'formatter': 'audit',
        }} if _log_file_ok else {}),
    },
    'root': {
        'handlers': ['console', *(['file'] if _log_file_ok else [])],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Django's request logger is noisy about 404s and says nothing this app
        # needs; its own errors still reach the root handlers.
        'django': {'level': 'WARNING'},
        # Who signed in and who was refused, and every time the database would
        # not take a time. Both belong in the application log.
        'apps.accounts.login': {'level': 'INFO'},
        'apps.timing': {'level': 'INFO'},
        # The audit trail goes to its own file *and nowhere else*: propagate off,
        # so a page of "user=x changed run 412" lines doesn't drown the log an
        # operator reads when something is wrong.
        'apps.audit': {
            'handlers': ['audit'] if _log_file_ok else [],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# --- Data directory permissions ---
# DATA_DIR holds every competitor's personal data, the audit trail and (in a
# development checkout) the signing key. Restricting it to the account that runs
# the server costs nothing and is done at startup — see config/datasecurity.py for
# why this rather than encryption at rest. Off only if a deployment manages its
# own ACLs and would rather this didn't touch them.
HARDEN_DATA_DIR = _env_bool('DJANGO_HARDEN_DATA_DIR', default=True)

# Local-memory cache, stated explicitly rather than left to the default: the login
# throttle keeps its counters here, and this app already runs as exactly one process
# (config/singleinstance.py), so per-process is per-system. A restart forgets the
# counters — acceptable, and the alternative is a database table per attempt.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'slalomtiming',
    }
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.competitions.context_processors.active_competition',
                'apps.accounts.context_processors.access',
                # Which sidebar entry is the current page (apps/nav.py) — worked
                # out from the resolved (app, url_name) pair rather than by
                # comparing url_name inline, which marked two entries at once.
                'apps.nav.context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# In-memory channel layer: fine for a single local process (one runserver/
# daphne instance). Swap for channels_redis if this ever runs multi-process.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
        # A blocked writer (the CP540 reader vs. a web request) waits for the lock
        # up to this long instead of failing immediately with "database is locked",
        # so an incoming timing signal isn't dropped under contention. WAL mode
        # (set per-connection in apps/timing/apps.py) lets readers not block it.
        'OPTIONS': {'timeout': 30},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _  # noqa: E402

# Default language for a visitor who hasn't chosen one. The app targets German
# slalom races, so German is the default; English is offered via the topbar
# language selector (django.views.i18n.set_language, wired in config/urls.py).
LANGUAGE_CODE = 'de'

# The languages the selector offers. Add a tuple here (plus a compiled
# locale/<code>/LC_MESSAGES/django.mo) to introduce another language later.
LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
]

# Where makemessages writes and compilemessages/LocaleMiddleware read the
# translation catalogs.
LOCALE_PATHS = [BASE_DIR / 'locale']

def _local_time_zone():
    """The zone this machine keeps, because that is the clock the operator reads.

    This app runs on a laptop at a venue. Every timestamp it shows — when the last
    backup was written, when somebody signed in, the audit trail — is read against
    the clock on the wall next to it, so a default of UTC is simply wrong by an hour
    or two all summer, in a way that is easy to misread as right.

    Django needs an IANA key, and Windows does not have one: it reports a localised
    display name ("Mitteleuropäische Sommerzeit"), which is neither a key nor stable
    across languages. tzlocal does the CLDR mapping, which is the whole reason it is
    a dependency. Failing that, UTC — a wrong clock is better than a server that
    won't start, and DJANGO_TIME_ZONE is the way to say it outright.
    """
    if (explicit := os.environ.get('DJANGO_TIME_ZONE')):
        return explicit
    try:
        import tzlocal

        return tzlocal.get_localzone_name() or 'UTC'
    except Exception:  # noqa: BLE001 - no zone is worth failing a boot over
        return 'UTC'


TIME_ZONE = _local_time_zone()

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Where `collectstatic` gathers every static file (this app's, the admin's) for
# WhiteNoise to serve. Required — without it collectstatic refuses to run, and with
# DEBUG off nothing serves /static/ at all. Gitignored; a deployment step, not a
# source directory: run `manage.py collectstatic` on every release (see DEPLOYMENT.md).
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT') or BASE_DIR / 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Hashes each file's contents into its name (so a changed stylesheet can be
    # cached forever yet never go stale on an operator's laptop) and pre-compresses
    # it. The hashed names only apply once collectstatic has run with DEBUG off;
    # in development the plain names are used.
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Uploaded media (results-PDF header/footer logos). Written at runtime, so
# WhiteNoise (which indexes STATIC_ROOT at startup) can't serve them — Django does,
# via config/urls.py. Set DJANGO_SERVE_MEDIA=False when a reverse proxy is
# configured to serve MEDIA_ROOT itself.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT') or DATA_DIR / 'media')
SERVE_MEDIA = _env_bool('DJANGO_SERVE_MEDIA', default=True)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Timing device connector
# Dotted path to the connector class used to receive events from the
# timing device. Swap this to point at a real hardware connector later
# without touching any code that consumes timing events.
TIMING_CONNECTOR = 'apps.timing.connectors.simulator.SimulatorConnector'
