"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    """Read a boolean from the environment ("1/true/yes/on" -> True)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """Read a comma-separated list from the environment (empties dropped)."""
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# --- Core security settings (see config/.env.example for deployment) ---
# In production every one of these MUST come from the environment. The literal
# fallbacks below only exist so a fresh local checkout runs with no setup — they
# are NOT safe to expose on a network.

# SECURITY WARNING: keep the secret key used in production secret!
INSECURE_DEV_SECRET_KEY = 'django-insecure-qvzii-zuntaf-+wv0yuv32g2vz%1)@mo4d7_a8n(bycgw&_@4o'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', INSECURE_DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local use; set DJANGO_DEBUG=False in any deployment.
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

# The checked-in development key is public — every copy of this repository has it,
# so sessions and password-reset tokens signed with it are forgeable. A deployment
# that forgot DJANGO_SECRET_KEY must fail loudly here rather than run unsafely
# (`check --deploy` only warns, and a warning is easy to miss on race morning).
if not DEBUG and SECRET_KEY == INSECURE_DEV_SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY is not set, so the insecure development key from the '
        'repository would be used with DEBUG=False. Generate one with:\n'
        '  uv run python -c "from django.core.management.utils import '
        'get_random_secret_key as g; print(g())"'
    )

# Hosts/domains this site may serve. Required (non-empty) once DEBUG is off.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Origins allowed to send authenticated POSTs over HTTPS (the live domain(s)),
# e.g. "https://timing.example.org". Needed for form posts from the real host.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    # 'daphne' must come first: it replaces `runserver` with an ASGI-capable
    # version so WebSocket upgrades (the live dashboard) actually work.
    # Without it, runserver silently falls back to plain WSGI and every
    # WebSocket connection fails immediately.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'apps.accounts',
    'apps.competitions',
    'apps.participants',
    'apps.timing',
    'apps.results',
    'apps.transfer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves everything under STATIC_ROOT (compressed + far-future cached) from the
    # app process itself. `runserver` stops serving /static/ once DEBUG is off, so
    # without this a real deployment renders with no CSS and no JS at all. Must sit
    # directly below SecurityMiddleware and above everything else.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Resolves the active language (session -> cookie -> Accept-Language ->
    # LANGUAGE_CODE) so {% trans %} and gettext render in the chosen language.
    # Must sit after SessionMiddleware (reads the language from the session) and
    # before CommonMiddleware.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Login required everywhere + role-based page gating (see apps/accounts).
    # Must sit after AuthenticationMiddleware (needs request.user).
    'apps.accounts.middleware.AccessControlMiddleware',
]

# Authentication redirects (apps.accounts provides the login/logout views).
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Shared secret an *unauthenticated* HTTP timing device must present on
# timing:signal (header "X-Device-Token"). Empty in local dev: while DEBUG is on
# the endpoint stays open, but a logged-in operator's browser (the Simulator)
# always works via its session. Set this in production so the one open write
# endpoint isn't world-writable. The real CP540 doesn't use this door (it feeds
# record_signal() directly from the reader thread), so this only matters for a
# future networked HTTP device.
TIMING_DEVICE_TOKEN = os.environ.get('TIMING_DEVICE_TOKEN', '')

# --- Production hardening ---
# All data pages already require a login (apps.accounts.AccessControlMiddleware),
# so nothing is world-readable. These transport-level protections switch on once
# DEBUG is off (a real deployment); serve the site behind HTTPS. Each HTTPS-only
# toggle can be overridden by env if you must run a deployment on plain HTTP
# (e.g. a trusted LAN) — but the secure default is HTTPS.
if not DEBUG:
    # Trust the X-Forwarded-Proto header from a TLS-terminating reverse proxy.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = _env_bool('DJANGO_SECURE_COOKIES', default=True)
    CSRF_COOKIE_SECURE = _env_bool('DJANGO_SECURE_COOKIES', default=True)
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # the JS timing views read the CSRF cookie
    X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.competitions.context_processors.active_competition',
                'apps.accounts.context_processors.access',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# In-memory channel layer: fine for a single local process (one runserver/
# daphne instance). Swap for channels_redis if this ever runs multi-process.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # A blocked writer (the CP540 reader vs. a web request) waits for the lock
        # up to this long instead of failing immediately with "database is locked",
        # so an incoming timing signal isn't dropped under contention. WAL mode
        # (set per-connection in apps/timing/apps.py) lets readers not block it.
        'OPTIONS': {'timeout': 30},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _  # noqa: E402

# Default language for a visitor who hasn't chosen one. The app targets German
# slalom races, so German is the default; English is offered via the topbar
# language selector (django.views.i18n.set_language, wired in config/urls.py).
LANGUAGE_CODE = 'de'

# The languages the selector offers. Add a tuple here (plus a compiled
# locale/<code>/LC_MESSAGES/django.mo) to introduce another language later.
LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
]

# Where makemessages writes and compilemessages/LocaleMiddleware read the
# translation catalogs.
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Where `collectstatic` gathers every static file (this app's, the admin's) for
# WhiteNoise to serve. Required — without it collectstatic refuses to run, and with
# DEBUG off nothing serves /static/ at all. Gitignored; a deployment step, not a
# source directory: run `manage.py collectstatic` on every release (see DEPLOYMENT.md).
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT') or BASE_DIR / 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Hashes each file's contents into its name (so a changed stylesheet can be
    # cached forever yet never go stale on an operator's laptop) and pre-compresses
    # it. The hashed names only apply once collectstatic has run with DEBUG off;
    # in development the plain names are used.
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Uploaded media (results-PDF header/footer logos). Written at runtime, so
# WhiteNoise (which indexes STATIC_ROOT at startup) can't serve them — Django does,
# via config/urls.py. Set DJANGO_SERVE_MEDIA=False when a reverse proxy is
# configured to serve MEDIA_ROOT itself.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT') or BASE_DIR / 'media')
SERVE_MEDIA = _env_bool('DJANGO_SERVE_MEDIA', default=True)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Timing device connector
# Dotted path to the connector class used to receive events from the
# timing device. Swap this to point at a real hardware connector later
# without touching any code that consumes timing events.
TIMING_CONNECTOR = 'apps.timing.connectors.simulator.SimulatorConnector'
