# Generated by Django 6.0.7 on 2026-07-12 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('intermediate', 'Intermediate')], max_length=20)),
                ('bib_number', models.PositiveIntegerField(blank=True, null=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.CharField(max_length=200)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timing_events', to='participants.participant')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['bib_number'], name='timing_timi_bib_num_776146_idx')],
            },
        ),
    ]
