# Generated by Django 6.0.7 on 2026-07-17 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('tp540', 'Tag Heuer TP540'), ('simulator', 'Simulator')], default='simulator', help_text='Which timing device signals are received from.', max_length=20)),
                ('start_channel', models.PositiveSmallIntegerField(default=1, help_text='Device channel that carries the start signal (0–9).', validators=[django.core.validators.MaxValueValidator(9)])),
                ('finish_channel', models.PositiveSmallIntegerField(default=2, help_text='Device channel that carries the finish signal (0–9).', validators=[django.core.validators.MaxValueValidator(9)])),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Network address of the Tag Heuer TP540.', null=True)),
            ],
            options={
                'verbose_name': 'timing settings',
                'verbose_name_plural': 'timing settings',
            },
        ),
        migrations.CreateModel(
            name='TimingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_number', models.PositiveIntegerField()),
                ('port', models.PositiveSmallIntegerField(help_text='Physical channel the signal came in on (1–4).')),
                ('is_manual', models.BooleanField(default=False)),
                ('device_time', models.TimeField(help_text='Wall-clock time the signal fired (hh:mm:ss.mmm).')),
                ('source', models.CharField(default='simulator', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
