# Generated by Django 6.0.7 on 2026-07-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_competitiontype_requires_license'),
        ('timing', '0002_timingsettings_timingsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingsignal',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timing_signals', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='timingsignal',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timingsignal',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TimedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_number', models.PositiveIntegerField(blank=True, null=True)),
                ('run_type', models.CharField(blank=True, choices=[('practice', 'Practice'), ('counted', 'Counted')], max_length=10)),
                ('run_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pylon_count', models.PositiveSmallIntegerField(default=0)),
                ('task_count', models.PositiveSmallIntegerField(default=0)),
                ('stopline_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_runs', to='competitions.competition')),
                ('competition_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.competitionclass')),
                ('start_signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='timing.timingsignal')),
            ],
        ),
    ]
