# Generated by Django 6.0.7 on 2026-07-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0003_timingsignal_competition_timingsignal_ignored_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timingsignal',
            name='order',
        ),
        migrations.AddField(
            model_name='timedrun',
            name='finish_signal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timing.timingsignal'),
        ),
        migrations.AlterField(
            model_name='timedrun',
            name='start_signal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timing.timingsignal'),
        ),
    ]
