# Generated by Django 6.0.7 on 2026-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0004_remove_timingsignal_order_timedrun_finish_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedrun',
            name='class_occurrence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
