# Generated by Django 6.0.7 on 2026-07-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_competition_auto_timing_order'),
        ('timing', '0005_timedrun_class_occurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarshalPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pylon_count', models.PositiveSmallIntegerField(default=0)),
                ('task_count', models.PositiveSmallIntegerField(default=0)),
                ('stopline_count', models.PositiveSmallIntegerField(default=0)),
                ('submitted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marshal_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='competitions.marshalpost')),
                ('timed_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marshal_penalties', to='timing.timedrun')),
            ],
            options={
                'unique_together': {('timed_run', 'marshal_post')},
            },
        ),
    ]
