# Generated by Django 6.0.7 on 2026-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0006_marshalpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='marshalpenalty',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timedrun',
            name='pylon_adjust',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedrun',
            name='task_adjust',
            field=models.IntegerField(default=0),
        ),
    ]
