# Generated by Django 6.0.7 on 2026-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0007_marshalpenalty_detail_timedrun_pylon_adjust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedrun',
            name='manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timedrun',
            name='manual_run_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timingsignal',
            name='entered',
            field=models.BooleanField(default=False),
        ),
    ]
