# Generated by Django 6.0.7 on 2026-07-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0008_timedrun_manual_entry_timedrun_manual_run_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedrun',
            name='stopline_adjust',
            field=models.IntegerField(default=0),
        ),
    ]
