# Generated by Django 6.0.7 on 2026-07-22 17:50

import django.core.validators
from django.db import migrations, models


def rename_tp540_to_cp540(apps, schema_editor):
    """The device was misnamed 'tp540'; the model is now 'cp540'. Migrate any
    existing settings row so the saved device isn't left as an unknown value."""
    TimingSettings = apps.get_model("timing", "TimingSettings")
    TimingSettings.objects.filter(device="tp540").update(device="cp540")


def rename_cp540_to_tp540(apps, schema_editor):
    TimingSettings = apps.get_model("timing", "TimingSettings")
    TimingSettings.objects.filter(device="cp540").update(device="tp540")


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0010_clear_derived_penalty_counts'),
    ]

    operations = [
        migrations.RunPython(rename_tp540_to_cp540, rename_cp540_to_tp540),
        migrations.AddField(
            model_name='timingsettings',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='TCP port of the Tag Heuer CP540.', null=True, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='device',
            field=models.CharField(choices=[('cp540', 'Tag Heuer CP540'), ('simulator', 'Simulator')], default='simulator', help_text='Which timing device signals are received from.', max_length=20),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Network address of the Tag Heuer CP540.', null=True),
        ),
    ]
