# Generated by Django 6.0.7 on 2026-07-22 18:38

import django.core.validators
from django.db import migrations, models


def backfill_cp540_defaults(apps, schema_editor):
    """Give the existing settings row the default CP540 address/port if it has
    none, so the fields aren't blank the first time the CP540 is selected."""
    TimingSettings = apps.get_model("timing", "TimingSettings")
    TimingSettings.objects.filter(ip_address__isnull=True).update(ip_address="192.168.1.50")
    TimingSettings.objects.filter(port__isnull=True).update(port=7000)


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0011_timingsettings_port_alter_timingsettings_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingsettings',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='192.168.1.50', help_text='Network address of the Tag Heuer CP540.', null=True),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=7000, help_text='TCP port of the Tag Heuer CP540.', null=True, validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.RunPython(backfill_cp540_defaults, migrations.RunPython.noop),
    ]
