# Generated by Django 6.0.7 on 2026-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0012_alter_timingsettings_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingsettings',
            name='ignore_incoming',
            field=models.BooleanField(default=False),
        ),
    ]
