# Generated by Django 6.0.7 on 2026-07-25 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0013_timingsettings_ignore_incoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingsettings',
            name='reader_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='device',
            field=models.CharField(choices=[('cp540', 'Tag Heuer CP540'), ('simulator', 'Simulator')], default='simulator', help_text='Which timing device signals are received from.', max_length=20, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='192.168.1.50', help_text='Network address of the Tag Heuer CP540.', null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=7000, help_text='TCP port of the Tag Heuer CP540.', null=True, validators=[django.core.validators.MaxValueValidator(65535)], verbose_name='Port'),
        ),
    ]
