# Generated by Django 6.0.7 on 2026-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_marshalpost_claim_seen_marshalpost_claim_token'),
        ('timing', '0014_timingsettings_reader_enabled_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timedrun',
            index=models.Index(fields=['competition', 'start_signal', 'finish_signal'], name='timedrun_comp_slots_idx'),
        ),
        migrations.AddIndex(
            model_name='timedrun',
            index=models.Index(fields=['competition', 'bib_number', 'competition_class', 'class_occurrence', 'run_type'], name='timedrun_comp_identity_idx'),
        ),
        migrations.AddIndex(
            model_name='timingsignal',
            index=models.Index(fields=['competition', 'ignored', '-received_at'], name='timingsignal_comp_ign_idx'),
        ),
    ]
