# Generated by Django 6.0.7 on 2026-07-26 04:53

import django.core.validators
from django.db import migrations, models


def reset_unusable_channels(apps, schema_editor):
    """Put a channel outside 1–4 back to the default it should have had.

    The field used to accept 0–9 while every supported device only has inputs
    1–4, so a stored 7 was a setting that could never match a signal — the rig
    was already recording nothing on it. Leaving it would also mean the settings
    page refuses to save until the operator notices, so the two documented
    defaults (start 1, finish 2) are restored instead.
    """
    TimingSettings = apps.get_model('timing', 'TimingSettings')
    for field, default in (('start_channel', 1), ('finish_channel', 2)):
        TimingSettings.objects.exclude(**{f'{field}__range': (1, 4)}).update(**{field: default})


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0015_timedrun_timedrun_comp_slots_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_unusable_channels, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timingsettings',
            name='finish_channel',
            field=models.PositiveSmallIntegerField(default=2, help_text='Device channel that carries the finish signal (1–4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='timingsettings',
            name='start_channel',
            field=models.PositiveSmallIntegerField(default=1, help_text='Device channel that carries the start signal (1–4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
