# Generated by Django 6.0.7 on 2026-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0016_alter_timingsettings_finish_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedrun',
            name='status',
            field=models.CharField(blank=True, choices=[('dnf', 'Did Not Finish'), ('dnc', 'Did Not Classify'), ('dns', 'Did Not Start'), ('dsq', 'Disqualified')], max_length=3),
        ),
    ]
