# Generated by Django 6.0.7 on 2026-07-28 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0017_timedrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedrun',
            name='finish_signal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='timing.timingsignal'),
        ),
        migrations.AlterField(
            model_name='timedrun',
            name='start_signal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='timing.timingsignal'),
        ),
    ]
