# Generated by Django 6.0.7 on 2026-07-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_number', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=1)),
                ('year_of_birth', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('club', models.CharField(blank=True, max_length=150)),
                ('nationality', models.CharField(blank=True, help_text='IOC country code, e.g. GER', max_length=3)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dns', 'Did Not Start'), ('dnf', 'Did Not Finish'), ('dsq', 'Disqualified'), ('finished', 'Finished')], default='registered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bib_number'],
            },
        ),
    ]
