# Generated by Django 6.0.7 on 2026-07-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_add_types_and_events'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='participant',
            name='competition_type',
            field=models.ForeignKey(help_text='Discipline this participant is registered under (e.g. Motorcycle, Go-Cart). A participant can only ever belong to one type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='competitions.competitiontype'),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dns', 'Did Not Start'), ('dnf', 'Did Not Finish'), ('dsq', 'Disqualified'), ('finished', 'Finished')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='participants.participant')),
            ],
            options={
                'ordering': ['bib_number'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'bib_number'), name='unique_bib_per_competition'), models.UniqueConstraint(fields=('competition', 'participant'), name='unique_participant_per_competition')],
            },
        ),
    ]
