# Generated by Django 6.0.7 on 2026-07-12 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_finalize_participant_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='notes',
        ),
        migrations.AddField(
            model_name='participant',
            name='address_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='address_street',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='participant',
            name='address_zip_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='participant',
            name='license_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='club',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
