# Generated by Django 6.0.7 on 2026-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_required_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_zip_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
