# Generated by Django 6.0.7 on 2026-07-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competition_allow_multiple_classes_and_more'),
        ('participants', '0006_drop_temporary_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='competitions.competitionclass')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='participants.participant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
