# Generated by Django 6.0.7 on 2026-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_classassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='co_driver_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='co_driver_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='vehicle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='club',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
