# Generated by Django 6.0.7 on 2026-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_participant_co_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
