# Generated by Django 6.0.7 on 2026-07-28 21:27

import apps.participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_alter_participant_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(validators=[apps.participants.models.validate_birth_date]),
        ),
    ]
