# Generated by Django 6.0.7 on 2026-07-30 19:08

import apps.participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_participant_last_used_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='club',
            field=models.CharField(blank=True, max_length=150, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='co_driver_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Co-driver first name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='co_driver_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Co-driver last name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(validators=[apps.participants.models.validate_birth_date], verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Licence number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='vehicle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vehicle'),
        ),
    ]
