# Generated by Django 6.0.7 on 2026-08-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_competition_uses_draw_numbers_and_more'),
        ('participants', '0012_alter_participant_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Draw number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_numbers', to='competitions.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_numbers', to='participants.participant')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'number'), name='unique_draw_number_per_competition'), models.UniqueConstraint(fields=('competition', 'participant'), name='unique_draw_participant_per_competition')],
            },
        ),
    ]
