# Generated by Django 6.0.7 on 2026-07-29 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Copy the database to the destination on a timer.')),
                ('destination', models.CharField(blank=True, help_text='Where the copies go — a USB stick or another drive, so a copy survives whatever happens to this computer.', max_length=500, verbose_name='Destination folder')),
                ('interval_minutes', models.PositiveSmallIntegerField(default=5, help_text='Minutes between copies (1–10).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Every')),
                ('keep', models.PositiveSmallIntegerField(default=12, help_text='How many copies to keep. Older ones are deleted.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Keep')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('last_file', models.CharField(blank=True, max_length=500)),
                ('last_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'backup settings',
                'verbose_name_plural': 'backup settings',
            },
        ),
    ]
